import numpy as np
std = np.sqrt(5)
sample = np.random.normal(5,std,1000)
max = np.max(sample)
min = np.min(sample)
mean = np.mean(sample)
sdd = np.std(sample)
prcnt = np.percentile(sample,[25,50,75])

print(f"最大值: {max:.3f}")
print(f"最小值: {min:.3f}")
print(f"均值: {mean:.3f}")
print(f"标准差: {sdd:.3f}")
print(f"四分位数 (25%, 50%, 75%): {prcnt[0]:.3f}, {prcnt[1]:.3f}, {prcnt[2]:.3f}")
print("数据类型:", sample.dtype)
print("内存大小 (bytes):", sample.nbytes)
sample_int32 = sample.astype(np.int32)
print("\n③ 转换后的数组信息：")
print("新数据类型:", samples_int32.dtype)
print("新内存大小 (bytes):", samples_int32.nbytes)